DROP TABLE IF EXISTS {OUTPUT_TABLE};

CREATE TABLE {OUTPUT_TABLE} AS
          SELECT 1 AS user_id
UNION ALL SELECT 1 AS user_id
UNION ALL SELECT 1 AS user_id
UNION ALL SELECT 2 AS user_id
UNION ALL SELECT 2 AS user_id
;
