DROP TABLE IF EXISTS {TMP_TABLE};

DROP TABLE IF EXISTS {THRESHOLD_TABLE};

CREATE TABLE {THRESHOLD_TABLE} AS
{THRESHOLD_STRING}
;

CREATE TABLE {TMP_TABLE} AS
SELECT 
    B.threshold,
    COUNT(CASE WHEN {TARGET_LABEL_COLUMN} = 1 AND {PREDICTION_COLUMN} > threshold THEN 1 END) AS TP,
    COUNT(CASE WHEN {TARGET_LABEL_COLUMN} = 0 AND {PREDICTION_COLUMN} > threshold THEN 1 END) AS FP,
    COUNT(CASE WHEN {TARGET_LABEL_COLUMN} = 0 AND {PREDICTION_COLUMN} < threshold THEN 1 END) AS TN,
    COUNT(CASE WHEN {TARGET_LABEL_COLUMN} = 1 AND {PREDICTION_COLUMN} < threshold THEN 1 END) AS FN
FROM {INPUT_TABLE} AS A CROSS JOIN {THRESHOLD_TABLE} AS B
GROUP BY threshold
;






