DROP TABLE IF EXISTS {MODEL_TMP_TABLE};

CREATE TABLE {MODEL_TMP_TABLE} AS
SELECT 
    B.threshold,
    COUNT(CASE WHEN {TARGET_LABEL_COLUMN} = 1 AND {PREDICTION_COLUMN} > threshold THEN 1 END) AS TP,
    COUNT(CASE WHEN {TARGET_LABEL_COLUMN} = 0 AND {PREDICTION_COLUMN} > threshold THEN 1 END) AS FP,
    COUNT(CASE WHEN {TARGET_LABEL_COLUMN} = 0 AND {PREDICTION_COLUMN} < threshold THEN 1 END) AS TN,
    COUNT(CASE WHEN {TARGET_LABEL_COLUMN} = 1 AND {PREDICTION_COLUMN} < threshold THEN 1 END) AS FN
FROM {INPUT_TABLE} AS A CROSS JOIN {THRESHOLD_TABLE} AS B
GROUP BY threshold
;
