DROP TABLE IF EXISTS {TMP_DB}.confusion_matrix;

CREATE TABLE {TMP_DB}.confusion_matrix AS
SELECT 
    B.threshold,
    COUNT(CASE WHEN A.{TARGET_LABEL_COLUMN} = 1 AND A.{PREDICTION_COLUMN} > threshold THEN 1 END) AS TP,
    COUNT(CASE WHEN A.{TARGET_LABEL_COLUMN} = 0 AND A.{PREDICTION_COLUMN} > threshold THEN 1 END) AS FP,
    COUNT(CASE WHEN A.{TARGET_LABEL_COLUMN} = 0 AND A.{PREDICTION_COLUMN} < threshold THEN 1 END) AS TN,
    COUNT(CASE WHEN A.{TARGET_LABEL_COLUMN} = 1 AND A.{PREDICTION_COLUMN} < threshold THEN 1 END) AS FN
FROM {INPUT_TABLE} AS A
CROSS JOIN {TMP_DB}.threshold_table AS B
GROUP BY threshold
;
