SELECT * FROM (SELECT * FROM {TASK_OUTPUT_TABLE}
            EXCEPT {DISTINCT_}
            SELECT * FROM {EXPECTED_OUTPUT_TABLE}) 
UNION ALL
SELECT * FROM (SELECT * FROM {EXPECTED_OUTPUT_TABLE}
            EXCEPT {DISTINCT_}
            SELECT * FROM {TASK_OUTPUT_TABLE})

