[DEFAULT]
# Fixed parameters for each database
gcp_project = avaus-academy
TMP_DB = tmp

## INPUT_DB = CUSTOMER_DB
## OUTPUT_DB = AB_TESTING_DB

# Removed from here, to be changable for each call
# PRIMARY_KEYS = ["customer_key"]
# STRATIFY_ON = ["age", "postal_code"]
# NBR_GROUPS = 2
