-- This sql file is not generalized and is geared toward GCP!
DROP TABLE IF EXISTS {TMP_DB}.{OUTPUT_TABLE};

CREATE TABLE {TMP_DB}.{OUTPUT_TABLE} AS
    (SELECT *, MOD(ROW_NUMBER() OVER (ORDER BY {STRATIFY_ON}), {NBR_GROUPS}) + 1 
        AS SGroups FROM {TMP_DB}.{INPUT_TABLE});

-- TEST
SELECT SGroups, COUNT(SGroups) FROM {TMP_DB}.{OUTPUT_TABLE} 
    GROUP BY SGroups;