test_name: Test 5
start_date: '2011-08-01'
end_date: '2011-08-31'
source_table: algo-factory-dev.instacart_tf.orders_unique
customer_key: order_id
metric_name: Average revenue
stratify_by:
- eval_set
- order_number
groups:
- name: A
  size: 0.5
  is_control: false
- name: B
  size: 0.3
  is_control: true
- name: C
  size: 0.2
  is_control: false