test_name: Test 4
start_date: '2011-08-01'
end_date: '2011-08-31'
source_table: algo-factory-dev.online_retail.online_retail_clv_clean
customer_key: customer_id
metric_name: Average revenue
groups:
- name: A
  size: 0.5
  is_control: false
- name: B
  size: 0.5
  is_control: true